### ISSUE TITLE
other services?

### ISSUE THREAD

**Issue by aurelpere** [juju4/ansible-harden-systemd#2]
Hi,

thanks for your ansible role, it is very helpful for me as i was searching for a role to implement the suggestions of systemd-analyze security. 

However, i dont find the resources to adapt your roles and understand better what to avoid with specific services for my basic config:

chrony.service                            8.2 EXPOSED   🙁
containerd.service                        9.6 UNSAFE    😨
cron.service                              9.6 UNSAFE    😨
dbus.service                              4.2 OK        🙂
docker.service                            9.6 UNSAFE    😨
emergency.service                         9.5 UNSAFE    😨
fail2ban.service                          9.6 UNSAFE    😨
getty@tty1.service                        9.6 UNSAFE    😨
lynis.service                             9.6 UNSAFE    😨
rc-local.service                          9.6 UNSAFE    😨
rescue.service                            9.5 UNSAFE    😨
resolvconf.service                        9.5 UNSAFE    😨
rsync.service                             3.2 OK        🙂
rsyslog.service                           2.1 OK        🙂
serial-getty@hvc0.service                 9.6 UNSAFE    😨
serial-getty@ttyS0.service                9.6 UNSAFE    😨
ssh.service                               9.6 UNSAFE    😨
systemd-ask-password-console.service      9.4 UNSAFE    😨
systemd-ask-password-wall.service         9.4 UNSAFE    😨
systemd-fsckd.service                     9.5 UNSAFE    😨
systemd-initctl.service                   9.4 UNSAFE    😨
systemd-journald.service                  4.3 OK        🙂
systemd-logind.service                    2.6 OK        🙂
systemd-networkd.service                  2.9 OK        🙂
systemd-udevd.service                     8.0 EXPOSED   🙁
unattended-upgrades.service               9.6 UNSAFE    😨
user@1000.service                         9.4 UNSAFE    😨
uuidd.service                             4.6 OK

**Comment by juju4** [comment]
Most of resources I used are listed in README references.
After, there is a lot of try and fail (really meaning A LOT...) and context adaptation.

My recommendations is to go to
* higher risks services, in my case, I prioritized network ones mostly.
* quick wins/feasible. typically, sshd and docker are imho not feasible to restrict easily without severly impacting them or outside of very specific context (for example, dedicated instance of sshd for only certain type of users and more restricted config).

security services may be good candidates, especially if not expecting any network activity.

**Comment by aurelpere** [comment]
hi, thanks for your reply. I used a bit the same settings as you used in networkmanager except for readwrite paths and resources allocation for sshd...it seems working well and lynis now tells me the service is less exposed...
cheers

**Comment by juju4** [comment]
sshd is difficult as depending on users and privileges, it may be required to have high privileges (installing packages, troubleshooting and so on) but depending on setup, that may go through other channel like automation with separate service.

Closing issue. Re-open if necessary.
